server {
  # Порт, который слушает Nginx внутри контейнера или на сервере
  listen 80;
  server_name localhost;

  # Путь к папке, где лежат файлы после vite build (папка dist)
  root /usr/share/nginx/html;
  index index.html;

  # SPA-роутинг
  location / {
    # Пытается найти файл по запросу. Если файла нет - отдает index.html
    try_files $uri $uri/ /index.html;
  }

  # Проксирование запросов к бэкенду, чтобы избежать CORS ошибок
  location /api/ {
    proxy_pass http://backend:8080; # адрес бэкенда
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}