services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: hack
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: hack_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U hack -d hack_db']
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - '8081:8080'

  redis:
    image: redis:8-alpine
    restart: always
    command: redis-server --save 60 1 --loglevel notice --requirepass redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a redis_password ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  backend:
    build:
      context: ./backend/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - '8080:8080'

  frontend:
    build:
      context: ./frontend/
    depends_on:
      - backend
    ports:
      - '3000:80'

volumes:
  pgdata:
  redis_data:
